openapi: 3.0.0
info:
  title: 채용 플랫폼 API
  version: 1.0.0
  description: 채용 플랫폼의 RESTful API 문서

servers:
  - url: http://113.198.66.75:18225
    description: 개발 서버

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        phone:
          type: string
        career:
          type: integer
        skillSet:
          type: array
          items:
            type: string
        lastLoginAt:
          type: string
          format: date-time

    Company:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        industry:
          type: string
        size:
          type: string
        location:
          type: string
        description:
          type: string
        logoUrl:
          type: string

    Job:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        requiredSkills:
          type: array
          items:
            type: string
        requiredCareer:
          type: integer
        salary:
          type: object
          properties:
            min:
              type: number
            max:
              type: number
        location:
          type: string
        jobType:
          type: string
          enum: [FULL_TIME, PART_TIME, CONTRACT, INTERNSHIP]
        status:
          type: string
          enum: [ACTIVE, CLOSED, DRAFT]
        viewCount:
          type: integer

    Application:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        jobId:
          type: string
          format: uuid
        status:
          type: string
          enum: [PENDING, REVIEWING, ACCEPTED, REJECTED]
        resumeUrl:
          type: string
        appliedAt:
          type: string
          format: date-time

paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: 회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                name:
                  type: string
                phone:
                  type: string
      responses:
        '201':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /api/jobs:
    get:
      tags:
        - Jobs
      summary: 채용 공고 목록 조회
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: location
          schema:
            type: string
        - in: query
          name: career
          schema:
            type: integer
        - in: query
          name: skills
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: 채용 공고 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
                  total:
                    type: integer
                  currentPage:
                    type: integer
                  totalPages:
                    type: integer

    post:
      tags:
        - Jobs
      summary: 채용 공고 등록
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      responses:
        '201':
          description: 채용 공고 등록 성공

  /api/applications:
    post:
      tags:
        - Applications
      summary: 채용 공고 지원
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jobId
              properties:
                jobId:
                  type: string
                  format: uuid
                resumeUrl:
                  type: string
      responses:
        '201':
          description: 지원 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'

    get:
      tags:
        - Applications
      summary: 내 지원 내역 조회
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [PENDING, REVIEWING, ACCEPTED, REJECTED]
      responses:
        '200':
          description: 지원 내역 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'

  /api/company-reviews:
    post:
      tags:
        - Company Reviews
      summary: 기업 리뷰 작성
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - companyId
                - rating
                - content
              properties:
                companyId:
                  type: string
                  format: uuid
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                content:
                  type: string
                pros:
                  type: string
                cons:
                  type: string
      responses:
        '201':
          description: 리뷰 작성 성공

  /api/interviews:
    post:
      tags:
        - Interviews
      summary: 면접 일정 등록
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - applicationId
                - scheduleDate
                - type
              properties:
                applicationId:
                  type: string
                  format: uuid
                scheduleDate:
                  type: string
                  format: date-time
                type:
                  type: string
                  enum: [ONLINE, OFFLINE, PHONE]
                location:
                  type: string
      responses:
        '201':
          description: 면접 일정 등록 성공

  /api/bookmarks:
    post:
      tags:
        - Bookmarks
      summary: 채용 공고 북마크
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jobId
              properties:
                jobId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: 북마크 토글 성공

    get:
      tags:
        - Bookmarks
      summary: 북마크 목록 조회
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 북마크 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'

security:
  - bearerAuth: []